### ISSUE TITLE
Push actual project code

### ISSUE THREAD

**Issue by SebastianZimmeck** [yinzhaowang/project-tutorial#1]
@yinzhaowang, it looks like the code is actual not the one from your project. If that is the case, you would need to push your code.

**Comment by yinzhaowang** [comment]
Professor, I uploaded the rest of codes for the website, and tested them. Those codes could present the web page.

**Comment by SebastianZimmeck** [comment]
Great! @yinzhaowang and @RodrigoRoman, feel free to open a new issue if you have a specific question, assign or mention me (@SebastianZimmeck), and point me to the relevant code related to the question.

Closing this issue since it is resolved.
